---
version: "3.5"
services:
  ambari-agent:
    image: ambari-agent:centos6
    hostname: ambari-agent
    environment:
      - PYTHONPATH=/usr/lib/ambari-agent/lib:/usr/lib/ambari-agent/lib/ambari_jinja2
      - AMBARI-AGENT.INI_server.hostname=ambari-server
      - ambariVersion
      - buildNumber
    env_file:
      - ambari-agent.ini.env
    volumes:
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-common/src/main/python:/usr/lib/ambari-agent/lib
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-agent/src/main/python/ambari_agent:/usr/lib/ambari-agent/lib/ambari_agent
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-agent/conf/unix:/usr/lib/ambari-agent/bin
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/src/main/resources:/opt/ambari-server/resources:ro
      - ./ambari-agent/start.sh:/start.sh:ro
    working_dir: /opt/ambari/ambari-agent
    command: /start.sh

  ambari-server:
    environment:
      AMBARI.PROPERTIES!CFG_agent.auto.cache.update: "false"
      AMBARI.PROPERTIES!CFG_java.home: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64
