---
version: "3.5"
services:
  ambari-server:
    image: ambari-server:dev
    hostname: ambari-server
    environment:
      CONF_DIR: /etc/ambari-server/conf
      PYTHONPATH: /usr/lib/ambari-server/lib
      AMBARI.PROPERTIES!CFG_server.os_type: alpine
      AMBARI.PROPERTIES!CFG_server.persistence.type: in-memory # default persistence, can be overwritten in other compose files
    env_file:
      - ambari.properties.env
    ports:
      - 5005:5005
      - 8080:8080
    volumes:
      - ${AMBARI_PROJECT:-~/src/ambari}:/opt/ambari:ro
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-common/src/main/python:/usr/lib/ambari-server/lib:delegated
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/src/main/python:/usr/lib/ambari-server/lib/ambari_server:delegated
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/target/classes:/var/lib/ambari-server/resources:delegated
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/src/main/resources/common-services:/var/lib/ambari-server/resources/common-services:ro
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/src/main/resources/stacks:/var/lib/ambari-server/resources/stacks:ro
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-server/src/main/resources/mpacks:/var/lib/ambari-server/resources/mpacks:ro
      - ${AMBARI_PROJECT:-~/src/ambari}/ambari-web/public:/usr/lib/ambari-server/web:delegated
      - ${AMBARI_OUTPUT:-~/tmp/ambari}/server/log:/var/log/ambari-server
      - ${AMBARI_OUTPUT:-~/tmp/ambari}/server/keys:/var/lib/ambari-server/keys
      - ~/.m2/repository:/opt/maven_repo:cached
    working_dir: /opt/ambari/ambari-server
