---
version: "3.5"
services:
  db:
    image: postgres:9
    hostname: db
    environment:
      POSTGRES_DB: ${AMBARI_DB_NAME:-ambari}
      POSTGRES_USER: ${AMBARI_DB_USER:-ambari}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    expose:
      - 5432
    ports:
      - 5432:5432
    secrets:
      - postgres-passwd
    volumes:
      - ${AMBARI_PROJECT}/ambari-server/target/classes/Ambari-DDL-Postgres-CREATE.sql:/docker-entrypoint-initdb.d/ambari.sql
    deploy:
      resources:
        limits:
          memory: 128M

  ambari-server:
    environment:
      AMBARI.PROPERTIES!CFG_server.jdbc.database: postgres
      AMBARI.PROPERTIES!CFG_server.jdbc.database_name: ${AMBARI_DB_NAME:-ambari}
      AMBARI.PROPERTIES!CFG_server.jdbc.driver: org.postgresql.Driver
      AMBARI.PROPERTIES!CFG_server.jdbc.hostname: db
      AMBARI.PROPERTIES!CFG_server.jdbc.port: 5432
      AMBARI.PROPERTIES!CFG_server.jdbc.url: jdbc:postgresql://db:5432/${AMBARI_DB_NAME:-ambari}
      AMBARI.PROPERTIES!CFG_server.jdbc.user.name: ${AMBARI_DB_USER:-ambari}
      AMBARI.PROPERTIES!CFG_server.persistence.type: remote
    secrets:
      - source: postgres-passwd
        target: /etc/ambari-server/conf/password.dat
        mode: 0400

secrets:
  postgres-passwd:
    file: password.dat
